### ISSUE TITLE
NestJS DevTools crash

### ISSUE THREAD

**Issue by JoDarma-lp** [nestjs/nest#12718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I try Devtool developper licence, and when I go to https://devtools.nestjs.com/ app crashed
<img width="1440" alt="Capture d’écran 2023-11-10 à 1 12 08 PM" src="https://github.com/nestjs/nest/assets/105506527/1caac6de-8b2e-4654-805a-31a13f77d684">
<img width="1440" alt="Capture d’écran 2023-11-10 à 1 12 26 PM" src="https://github.com/nestjs/nest/assets/105506527/8b0891f8-1938-40f3-b0cd-a3566ce81160">

I use NestJS on docker container 

docker-compose.yml : 
```
api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    networks:
      - api-network
    environment:
      ...
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3001:3000
      - 8000:8000
```

My Dockerfile : 

```
EXPOSE 3000
EXPOSE 8000
```

My app.module.ts : 

```
DevtoolsModule.register({
                    http: true,
                    port: 8000
                }),
```

main.ts 

```
  const app = await NestFactory.create(AppModule, {
        forceCloseConnections: true,
        rawBody: true,
        snapshot: true,
    });
```

What is my mistake on the configuration of devtool ? 

### Minimum reproduction code

no

### Expected behavior

Devtool not crash

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/devtools-integration

### NestJS version

^10.2.7

### Packages versions

```
 "@nestjs-modules/mailer": "^1.8.1",
  "@nestjs/axios": "^3.0.0",
  "@nestjs/bull": "^10.0.1",
  "@nestjs/cli": "^10.0.0",
  "@nestjs/common": "^10.2.7",
  "@nestjs/config": "^3.0.0",
  "@nestjs/core": "^10.2.7",
  "@nestjs/devtools-integration": "^0.1.5",
  "@nestjs/event-emitter": "^2.0.2",
  "@nestjs/jwt": "^10.1.0",
  "@nestjs/mapped-types": "*",
  "@nestjs/microservices": "^10.0.0",
  "@nestjs/passport": "^10.0.0",
  "@nestjs/platform-express": "^10.0.0",
  "@nestjs/schematics": "^10.0.0",
  "@nestjs/swagger": "^7.0.1",
  "@nestjs/terminus": "^10.1.1",
  "@nestjs/testing": "^10.0.0",
  "@nestjs/typeorm": "^10.0.0",
```

### Node.js version

10.1.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux
