### ISSUE TITLE
Can't debug nest app.

### ISSUE THREAD

**Issue by Ayzrian** [nestjs/nest#3638]
## Current behavior

I am trying to debug my nest app, but I can't connect to it.
First of all, i start my app inside docker container. Here is my docker-compose.yml.
```yml
version: "3"
services:
  node:
    image: node
    container_name: node
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9222:9222
      - 9229:9229
    volumes:
      - ./src:/src
    working_dir: /src
    command: npm start
    tty: true
```
Command npm start is set as  nest start --watch --debug.

I get message inside console. 

![image](https://user-images.githubusercontent.com/44115170/70815401-102fdb00-1dd6-11ea-8066-16df347be22d.png)

I set up Webstorm to debug node.

![image](https://user-images.githubusercontent.com/44115170/70815437-25a50500-1dd6-11ea-8bac-97be7ffc8f7f.png)

And when I trying to debug app, I stuck with connection to node.

![image](https://user-images.githubusercontent.com/44115170/70815519-538a4980-1dd6-11ea-9330-3b45e6a92c60.png)

## Expected behavior
I want to be able to connect to my app and debug it.

## Environment

<pre><code>
Nest version: 6.9

 
For Tooling issues:
- Node version: 12.12 
- Platform: Windows 

Others:
Webstorm
Docker

</code></pre>
