### ISSUE TITLE
 TypeError: Right-hand side of 'instanceof' is not an object when use absolute path in nestjs

### ISSUE THREAD

**Issue by chungchi300** [nestjs/nest#4089]
## Current behavior
```
  ● Test suite failed to run

    TypeError: Right-hand side of 'instanceof' is not an object

       7 | export class PhotoService {
       8 |   constructor(
    >  9 |     @InjectRepository(Photo)
         |      ^
      10 |     private readonly photoRepository: Repository<Photo>,
      11 |   ) {}
      12 | 

      at Object.getRepositoryToken (node_modules/@nestjs/typeorm/dist/common/typeorm.utils.js:16:26)
      at Object.<anonymous>.exports.InjectRepository (node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.js:6:130)
      at Object.<anonymous> (src/typeormAndJest/exp/photo/photo.service.ts:9:6)
      at Object.<anonymous> (src/typeormAndJest/exp/photo/photo.module.ts:2:1)

```

## Input Code
https://github.com/chungchi300/typescript-starter

```ts
//at src/typeormAndJest/typeorm.spec.ts
import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import * as request from 'supertest';

import { AsyncApplicationModule } from 'src/typeormAndJest/exp/app-async.module';
import { author } from 'src/deep/deep2/util';
describe('TypeOrm', () => {
  let server;
  let app: INestApplication;

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      imports: [AsyncApplicationModule],
    }).compile();

    app = module.createNestApplication();
    server = app.getHttpServer();
    await app.init();
  });

  it(`should return created entity`, () => {
    expect(author()).toBe('jeff chung');
    // return request(server)
    //   .post('/photo')
    //   .expect(201, { name: 'Nest', description: 'Is great!', views: 6000 });
  });

  afterEach(async () => {
    // await app.close();
  });
});

```

## Expected behavior
The test should run successfully
## Environment

```
services:
  db:
    #build: https://github.com/guillaumeprevost/docker-mysql-utf8mb4
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856
    environment:
      - MYSQL_DATABASE=nestBoilerplate
      - MYSQL_ROOT_PASSWORD=dockerPassword
    ports:
      - '3306:3306'
```
