### ISSUE TITLE
Getting error in AWS Lambda: "class-transformer" package is missing. make sure to install this library to take advantage of ValidationPipe

### ISSUE THREAD

**Issue by Suedo** [nestjs/nest#4954]
### Bug Report
Similar to #1386 

### Current behavior
I am deploying a very basic Nestjs todo-list kindof app via Serverless framework, and using serverless webpack to bundle it. Only when I try to use a Validation Pipe, this problem occurs in the deployed Lambda function. This is not a problem in my local.

I have not yet implemented the workaround mentioned in [one of the comments](https://github.com/nestjs/nest/issues/1386#issuecomment-461914216) , but I feel Ideally I should not need to. The original ticket is closed, mentioning that Nest v6 and above should fix this, But I am using Nest v7 at the moment, and the problem persists.

[Github repo](https://github.com/Suedo/nestjs-serverless)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Suedo** [comment]
@kamilmysliwiec But why is this not a Bug ?

**Comment by MaxVynohradov** [comment]
@Suedo Maybe too late, but anyway.  It's normal behavior of nest.js. To fix this issue you should force add this dependency, literally - update serverless-webpack config, smth like this:
 
```yml
custom:
  stage: development
  webpack:
    webpackConfig: ./sls.webpack.config.js
    includeModules:
      forceInclude:
        - class-transformer
```
