### ISSUE TITLE
Support Plug-N-Play (Yarn v2)

### ISSUE THREAD

**Issue by brandon-leapyear** [nestjs/nest#5836]
## Current behavior
Running tests with yarn version 2 fails with a bunch of errors like
```
The "@nestjs/platform-express" package is missing. Please, make sure to install this library ($ npm install @nestjs/platform-express) to take advantage of NestFactory.
```
Yarn version 2 started using the Plug-n-Play API, which prevents packages from `require`-ing dependencies not explicitly listed in the package's `package.json`. I'm not sure what the best solution is, but one solution is to add `@nestjs/platform-express` as a peer dependency for `@nestjs/testing`. This workaround works for me

```yaml
# .yarnrc.yml
packageExtensions:
  '@nestjs/testing@*':
    peerDependencies:
      '@nestjs/platform-express': '*'
```

## Input Code

```ts
const your = (code) => here;
```

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
