### ISSUE TITLE
npm run start:dev apparently uses polling file watcher which leads to very high CPU usage on Docker for Mac

### ISSUE THREAD

**Issue by dschuessler** [nestjs/nest#6325]
## Bug Report

Steps to reproduce:
1. Create a new nest project with `npx @nestjs/cli new`
2. Start the project with `npm run start:dev`

## Current behavior

Node uses about 4% of the CPU when running `npm run start:dev`. This amounts to 30-40% of the CPU when running the same project in a container on Docker for Mac. I watched this go up to 60-70% of the CPU when running medium sized NestJS projects on Docker for Mac just for watching files. (The app itself is idling.)

## Expected behavior

`nest start --watch` uses no CPU for watching files at all. Nodemon can do so. Just run `npm install nodemon --save-dev` and replace the `start:dev` script in `package.json` with `nodemon --exec npx nest start -e ts --watch src`.

## Input Code

The `docker-compose.yml` I used to measure CPU usage on Docker for Mac

```yml
version: "3"
services:
  nest-app:
    container_name: nest-app
    image: node:14-buster
    volumes:
      - ./:/api:cached
    working_dir: /api
    command: npm run start:dev
```

Put it at the root of the NestJS project and run `docker-compose up`.

## Possible Solution

Do not use a polling file watcher.

Since improving file system performance of Docker for Mac seems to be a major engineering hurdle, just not using a polling file watcher seems to be a comparatively simple solution for making NestJS development bearable on Docker for Mac without using external dependencies like nodemon. Thus I open the ticket here.

## Environment

<pre><code>
Nest version: 7.5.1

 
For Tooling issues:
- Node version: 14  
- Platform: macOS 11.1 

Others:
Docker for Mac: 3.1.0

</code></pre>
