### ISSUE TITLE
Dark Mode for Documentation pages

### ISSUE THREAD

**Issue by ZackPoorman** [nestjs/nest#9078]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The documentation pages are light theme/mode only.

### Describe the solution you'd like

Add a toggle to the documentation pages so the user can control the theme.

### Teachability, documentation, adoption, migration strategy

Click a toggle which changes the theme from light to dark.

### What is the motivation / use case for changing the behavior?

Ease of reading the documentation

**Comment by jmcdo29** [comment]
[There is a PR for this, but I believe it needs to be revisted](https://github.com/nestjs/docs.nestjs.com/pull/1138)

**Comment by micalevisk** [comment]
I've been using the following CSS rules [adapted from this one](https://www.reddit.com/r/Nestjs_framework/comments/iz8hdh/dark_stylish_theme_for_nestjs_documentation) with [Code Injector](https://github.com/Lor-Saba/Code-Injector) extension.

<details>
<summary>CSS</summary>

```css
body {
  background-color: #2c2c2c;
}

app-menu.ps {
  background-color: #272727;
}
.btn-support {
  background-color: transparent !important;
}
.page-wrapper,
.page-wrapper h1,
.page-wrapper h2,
.page-wrapper h3,
.page-wrapper h4,
.page-wrapper h5,
.page-wrapper h6 {
  color: #cfcfcf !important;
}
li a,
app-menu-item * {
  color: #cfcfcf !important;
}
/*
*:not(.language-typescript *) {
  color: #cfcfcf !important;
}
*/
strong {
  color: #d7d5d5 !important
}

code {
  background-color: #37372e;
}

p code,
blockquote,
blockquote[class],
pre {
  background-color: #37372e !important;
}

blockquote[class] code,
.file-tree {
  border-color: transparent;
  background-color: #3a3a37 !important;
}

tr:nth-of-type(2n) td {
  background-color: rgba(255, 255, 255, 0.02) !important;
}
table tr th {
  background-color: rgba(255, 255, 255, 0.06) !important;
}

[class] app-header {
  background-color: #151515;
}
div.menu-wrapper * {
  background-color: rgba(1, 1, 1, 0.2) !important;
}
div.newsletter-wrapper {
  background-color: #292a25 !important;
}
.envelope-bg {
  opacity: 0.02;
}
pre.language-typescript {
  background-color: #2b2b2b !important;
}
.language-typescript {
  color: #a9b7c6;
}
.token.number {
  color: #6897bb;
}
.token.keyword {
  color: #cb772f;
}
.token.punctuation {
  color: #a9b7c6;
}
.token.function {
  color: #ffc66d;
}
.token.string {
  color: #698657;
}
```

</details>

<details> <summary>preview</summary>

![image](https://user-images.githubusercontent.com/13461315/152047158-f14d1597-d094-4b13-9464-35e357877b79.png)

<details>
